version: '3.1'
services:

  postgresql:
    image: postgres:12-alpine
    ports:
      - '3306:3306'
    volumes:
    - ./data:/var/lib/postgresql
    environment:
      POSTGRES_USER: Tatiana
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TanyaDB





